# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AirDC++ Web Client
description: > # this means to ignore newlines until "baseurl:"
  A peer-to-peer file sharing client with a responsive web user interface for frequent sharing of files and directories within groups of people.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://airdcpp-web.github.io" # the base hostname & protocol for your site
github_username: airdcpp-webclient
excerpt_separator: <!--more-->
timezone: Europe/Helsinki


# Build settings
markdown: kramdown

collections:
  docs:
    output: true

plugins:
  - jekyll-feed